# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # Run go mod tidy for each subproject
    - sh -c 'cd wg-drill-client && go mod tidy'
    - sh -c 'cd wg-drill-server && go mod tidy'
    # Run go generate for each subproject
    - sh -c 'cd wg-drill-client && go generate ./...'
    - sh -c 'cd wg-drill-server && go generate ./...'

builds:
  - id: wg-drill-client
    main: main.go
    binary: wg-drill-client
    dir: wg-drill-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - mips
      - mips64

  - id: wg-drill-server
    main: main.go
    binary: wg-drill-server
    dir: wg-drill-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - mips
      - mips64

archives:
  - id: wg-drill-client
    builds:
      - wg-drill-client
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      wg-drill-client-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: wg-drill-server
    builds:
      - wg-drill-server
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      wg-drill-server-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

upx:
  - # Whether to enable it or not.
    #
    # Templates: allowed (since v1.21)
    enabled: true

    # Filter by build ID.
    ids:
      - wg-drill-client
      - wg-drill-server

    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - mips

    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: "9"

    # Whether to try LZMA (slower).
    lzma: false

    # Whether to try all methods and filters (slow).
    brute: false
# checksum:
#   name_template: "{{ .ProjectName }}-client-{{ .Version }}_checksums.txt"
