#!/bin/sh /etc/rc.common
# OpenWrt init script for natdrill-procd (procd)

USE_PROCD=1
START=99
STOP=10

PROG=/usr/bin/wg-natdrill-plugin
NAME=natdrill-daemon

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" daemon
	# 自动重启，默认退避
	procd_set_param respawn
	# 输出到系统日志
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	# 由 procd 管理，无需手动 killall
	return 0
}
